version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env.db

  web:
    env_file: .env.web
    build: .
    command: gunicorn --bind 0.0.0.0:8000 gshop_backend.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db