# Generated by Django 3.1.1 on 2021-05-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='24d0b24b0d448aa2362d', editable=False, max_length=20),
        ),
    ]
