# Generated by Django 3.1.1 on 2021-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210506_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='4b3fd803031d513732fb', editable=False, max_length=20),
        ),
    ]
