# Generated by Django 3.1.1 on 2021-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210506_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=34),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='32bddb28910cd9c0e726', editable=False, max_length=20),
        ),
    ]
