# Generated by Django 3.1.1 on 2021-05-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210506_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default='3210458cec76797d609d', editable=False, max_length=20),
        ),
    ]
